-- Schéma initial : tables de l'exemple de référence. Ne jamais modifier une migration appliquée (FLY-001).

CREATE TABLE note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
