// Contexte passé aux templates (`it`). Construit une seule fois par composition : valeurs du
// scaffold, agrégats additifs des contributions (Maven, propriétés Spring, env), aides de
// typage SQL/Java. Les templates d'un profil n'accèdent jamais à `it.options` ni ceux d'une
// option à `it.profile` (vérifié par `check:content`).
import { stringify } from 'yaml';
import type {
  Column,
  EnvVar,
  Language,
  LocalizedText,
  MavenBom,
  MavenDependency,
  PropertyTree,
  Table,
} from '../catalog/schema.js';
import type { Database, Scaffold } from '../config/schema.js';

export interface ProjectContext {
  name: string;
  description: string;
  basePackage: string;
  basePackagePath: string;
  /** Préfixe des classes racines : `pay-flow` → `PayFlow`. */
  className: string;
  groupId: string;
  artifactId: string;
  /** Nom de base de données par défaut : `pay-flow` → `pay_flow`. */
  dbName: string;
}

export interface LayerContext {
  id: string;
  package: string;
  mayDependOn: string[];
}

export interface MavenContext {
  boms: MavenBom[];
  dependencies: MavenDependency[];
  properties: Record<string, string>;
}

export interface PropertiesContext {
  main: PropertyTree;
  test: PropertyTree;
  /** Documents `spring.config.activate.on-profile`, par nom de profil Spring. */
  profiles: Record<string, PropertyTree>;
}

export interface ProfileInfo {
  id: string;
  version: string;
  summary: string;
  whenToUse: string[];
  whenNotToUse: string[];
}

/** Valeurs saisies au questionnaire mais absentes de `scaffold.yaml` (ne servent qu'à `init`). */
export interface ComposeExtras {
  /** Valeurs d'exemple à substituer dans `.env.example`, par nom de variable. */
  envOverrides?: Record<string, string> | undefined;
}

/** Versions épinglées par l'outil (CLAUDE.md §5 : la version de Spring Boot n'est pas demandée). */
export const PINNED_VERSIONS = {
  springBoot: '4.1.1',
  archunit: '1.5.0',
  spotlessPlugin: '3.10.1',
  springModulith: '2.1.1',
  mavenWrapper: '3.3.4',
  maven: '3.9.16',
} as const;
export type PinnedVersions = typeof PINNED_VERSIONS;

export interface TemplateContext {
  project: ProjectContext;
  stack: { java: 21 | 17; database: Database; migrations: string | null };
  profile: string;
  profileInfo: ProfileInfo;
  options: Scaffold['options'];
  optionIds: string[];
  git: { author: { name: string; email: string }; agentTrailer: boolean };
  language: { comments: Language; docs: Language };
  maven: MavenContext;
  properties: PropertiesContext;
  env: EnvVar[];
  tables: Table[];
  layers: LayerContext[];
  toolVersion: string;
  /** Date du jour (AAAA-MM-JJ), injectable pour des rendus déterministes. */
  today: string;
  versions: PinnedVersions;
  extras: ComposeExtras;
  /** Texte dans la langue des commentaires. */
  t: (fr: string, en: string) => string;
  /** Texte dans la langue de la documentation. */
  d: (fr: string, en: string) => string;
  /** Texte localisé du catalogue, dans la langue de la documentation. */
  text: (value: LocalizedText) => string;
  /** Sérialise un objet en YAML (sans document marker, sans retour final). */
  yaml: (value: unknown) => string;
  /** Fusion profonde additive (conflit sur une feuille différente), pour composer les propriétés Spring. */
  merge: (base: PropertyTree, contribution: PropertyTree) => PropertyTree;
  sqlType: (column: Column) => string;
  javaType: (column: Column) => string;
  liquibaseType: (column: Column) => string;
}

export function toClassName(kebab: string): string {
  return kebab
    .split('-')
    .filter((s) => s.length > 0)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

export function sqlTypeFor(column: Column, database: Database): string {
  const length = column.length ?? 255;
  switch (database) {
    case 'postgresql':
      return {
        identity: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        string: `VARCHAR(${length})`,
        text: 'TEXT',
        integer: 'INTEGER',
        bigint: 'BIGINT',
        boolean: 'BOOLEAN',
        timestamp: 'TIMESTAMP WITH TIME ZONE',
        date: 'DATE',
        decimal: 'DECIMAL(19, 4)',
      }[column.type];
    case 'mysql':
      return {
        identity: 'BIGINT AUTO_INCREMENT PRIMARY KEY',
        string: `VARCHAR(${length})`,
        text: 'TEXT',
        integer: 'INT',
        bigint: 'BIGINT',
        boolean: 'BOOLEAN',
        timestamp: 'DATETIME(6)',
        date: 'DATE',
        decimal: 'DECIMAL(19, 4)',
      }[column.type];
    case 'oracle':
      return {
        identity: 'NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        string: `VARCHAR2(${length} CHAR)`,
        text: 'CLOB',
        integer: 'NUMBER(10)',
        bigint: 'NUMBER(19)',
        boolean: 'NUMBER(1)',
        timestamp: 'TIMESTAMP(6) WITH TIME ZONE',
        date: 'DATE',
        decimal: 'NUMBER(19, 4)',
      }[column.type];
    case 'none':
      return '';
  }
}

export function javaTypeFor(column: Column): string {
  return {
    identity: 'Long',
    string: 'String',
    text: 'String',
    integer: 'Integer',
    bigint: 'Long',
    boolean: 'Boolean',
    timestamp: 'Instant',
    date: 'LocalDate',
    decimal: 'BigDecimal',
  }[column.type];
}

export function liquibaseTypeFor(column: Column): string {
  const length = column.length ?? 255;
  return {
    identity: 'BIGINT',
    string: `VARCHAR(${length})`,
    text: 'CLOB',
    integer: 'INT',
    bigint: 'BIGINT',
    boolean: 'BOOLEAN',
    timestamp: 'TIMESTAMP WITH TIME ZONE',
    date: 'DATE',
    decimal: 'DECIMAL(19, 4)',
  }[column.type];
}

export function yamlText(value: unknown): string {
  return stringify(value, { lineWidth: 0 }).replace(/\n$/, '');
}
