// Le plan : liste d'opérations calculée sans rien écrire (CLAUDE.md §7). Une étape séparée
// (`execute.ts`) l'applique. Vocabulaire :
//   create        le fichier n'existe pas → sera écrit
//   update        généré, intact depuis la dernière génération, contenu différent → sera réécrit
//   unchanged     rien à faire (identique, ou fichier d'équipe déjà présent)
//   skip-modified généré mais modifié ou supprimé par l'équipe → signalé, jamais touché
//   conflict      existe sur le disque sans être connu du manifeste → signalé, jamais touché
//   delete        généré autrefois, intact, plus produit par la source → sera supprimé
import type { FileSystem } from '../fs/types.js';
import { joinPath } from '../fs/types.js';
import { hashContent } from './hash.js';
import { manifestIndex, type Manifest } from './manifest.js';
import type { GeneratedFile } from './render.js';

export type OperationKind =
  'create' | 'update' | 'unchanged' | 'skip-modified' | 'conflict' | 'delete';

export interface Operation {
  kind: OperationKind;
  path: string;
  /** Contenu à écrire (absent pour `delete` et pour les fichiers non générés cette fois). */
  content?: string | undefined;
  hash: string;
  owner: 'generated' | 'team';
  source: string;
  /** Précision lisible : `deleted by team`, `team-owned`, `no longer generated`… */
  reason?: string | undefined;
}

export interface Plan {
  operations: Operation[];
  /** Manifeste à écrire une fois le plan exécuté. */
  manifest: Manifest;
  summary: Record<OperationKind, number>;
}

export interface PlanMeta {
  scaffoldVersion: string;
  profileVersion: string;
}

export const OPERATION_KINDS: readonly OperationKind[] = [
  'create',
  'update',
  'unchanged',
  'skip-modified',
  'conflict',
  'delete',
];

function emptySummary(): Record<OperationKind, number> {
  return { create: 0, update: 0, unchanged: 0, 'skip-modified': 0, conflict: 0, delete: 0 };
}

export async function buildPlan(
  fs: FileSystem,
  projectDir: string,
  files: readonly GeneratedFile[],
  previous: Manifest | undefined,
  meta: PlanMeta,
): Promise<Plan> {
  const known = manifestIndex(previous);
  const operations: Operation[] = [];
  const nextEntries = new Map<string, string>();
  const generatedPaths = new Set<string>();

  for (const file of files) {
    const path = file.path;
    const hash = hashContent(file.content);
    const onDisk = await fs.readText(joinPath(projectDir, path));
    const base = { path, content: file.content, hash, owner: file.owner, source: file.source };

    if (file.owner === 'team') {
      operations.push(
        onDisk === undefined
          ? { ...base, kind: 'create' }
          : { ...base, kind: 'unchanged', reason: 'team-owned' },
      );
      continue;
    }

    generatedPaths.add(path);
    const previousHash = known.get(path);

    if (onDisk === undefined) {
      if (previousHash !== undefined) {
        operations.push({ ...base, kind: 'skip-modified', reason: 'deleted by team' });
        nextEntries.set(path, previousHash);
      } else {
        operations.push({ ...base, kind: 'create' });
        nextEntries.set(path, hash);
      }
      continue;
    }

    const diskHash = hashContent(onDisk);
    if (previousHash === undefined) {
      if (diskHash === hash) {
        operations.push({ ...base, kind: 'unchanged', reason: 'identical, adopted' });
        nextEntries.set(path, hash);
      } else {
        operations.push({ ...base, kind: 'conflict', reason: 'exists, not generated by prepwork' });
      }
      continue;
    }

    if (diskHash !== previousHash) {
      operations.push({ ...base, kind: 'skip-modified', reason: 'modified by team' });
      nextEntries.set(path, previousHash);
      continue;
    }
    operations.push({ ...base, kind: diskHash === hash ? 'unchanged' : 'update' });
    nextEntries.set(path, hash);
  }

  // Fichiers du manifeste précédent que la source ne produit plus.
  for (const [path, previousHash] of known) {
    if (generatedPaths.has(path)) continue;
    const onDisk = await fs.readText(joinPath(projectDir, path));
    const base = { path, hash: previousHash, owner: 'generated' as const, source: 'manifest' };
    if (onDisk === undefined) {
      operations.push({
        ...base,
        kind: 'unchanged',
        reason: 'no longer generated, already absent',
      });
    } else if (hashContent(onDisk) === previousHash) {
      operations.push({ ...base, kind: 'delete', reason: 'no longer generated' });
    } else {
      operations.push({
        ...base,
        kind: 'skip-modified',
        reason: 'no longer generated, modified by team',
      });
      nextEntries.set(path, previousHash);
    }
  }

  operations.sort((a, b) => a.path.localeCompare(b.path));
  const summary = emptySummary();
  for (const operation of operations) summary[operation.kind] += 1;

  return {
    operations,
    manifest: {
      scaffold_version: meta.scaffoldVersion,
      profile_version: meta.profileVersion,
      files: [...nextEntries.entries()].map(([path, hash]) => ({ path, hash })),
    },
    summary,
  };
}
