# yaml-language-server: $schema=../../../../schema/aspnet/files.schema.json
files:
  - source: Dockerfile.eta
    target: Dockerfile
  - source: compose.yaml.eta
    target: compose.yaml
  - source: .dockerignore.eta
    target: .dockerignore
