"""PERS-001 : la migration livrée décrit exactement le modèle.

`alembic check` exige une base vivante — contrairement à son équivalent EF Core —
donc ce contrôle appartient au niveau intégration, pas au pipeline hors Docker.
"""

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected


@pytest.mark.integration
def test_the_shipped_migration_matches_the_model(database_url: str) -> None:
    """Un écart ici est un faux diff à la prochaine migration, pas une erreur visible."""
    try:
        command.check(Config("alembic.ini"))
    except AutogenerateDiffsDetected as difference:  # pragma: no cover
        pytest.fail(f"le modèle et les migrations divergent : {difference}")
