// Contexte de templates du pack `spring-boot` : agrégats additifs des contributions (Maven,
// propriétés Spring), aides de typage SQL/Java, versions épinglées.
import { evaluateCondition } from '../../catalog/condition.js';
import { PrepworkError } from '../../errors.js';
import type { BaseTemplateContext, TemplateContext } from '../../engine/context.js';
import { cloneTree, mergeTree } from '../../engine/tree.js';
import type { PackContextInput } from '../types.js';
import {
  BASE_PACKAGE_PLACEHOLDER,
  mavenOf,
  propertiesOf,
  tablesOf,
  type Column,
  type MavenBom,
  type MavenContribution,
  type MavenDependency,
  type PropertiesContribution,
  type Table,
} from './catalog.js';
import { asSpringScaffold, type Database } from './scaffold.js';

/** Versions épinglées par l'outil (CLAUDE.md §5 : la version de Spring Boot n'est pas demandée). */
export const PINNED_VERSIONS = {
  springBoot: '4.1.1',
  archunit: '1.5.0',
  spotlessPlugin: '3.10.1',
  springModulith: '2.1.1',
  mavenWrapper: '3.3.4',
  maven: '3.9.16',
} as const;
export type PinnedVersions = typeof PINNED_VERSIONS;

export interface MavenContext {
  boms: MavenBom[];
  dependencies: MavenDependency[];
  properties: Record<string, string>;
}

export interface PropertiesContext {
  main: Record<string, unknown>;
  test: Record<string, unknown>;
  /** Documents `spring.config.activate.on-profile`, par nom de profil Spring. */
  profiles: Record<string, Record<string, unknown>>;
}

function conflict(message: string): PrepworkError {
  return new PrepworkError('COMPOSITION_CONFLICT', message);
}

export function mergeMaven(
  contributions: readonly [string, MavenContribution | undefined][],
  conditionContext: Record<string, unknown>,
): MavenContext {
  const boms = new Map<string, [string, MavenBom]>();
  const dependencies = new Map<string, [string, MavenDependency]>();
  const properties = new Map<string, [string, string]>();
  for (const [label, contribution] of contributions) {
    if (!contribution) continue;
    for (const bom of contribution.boms) {
      const key = `${bom.group_id}:${bom.artifact_id}`;
      const previous = boms.get(key);
      if (previous && previous[1].version !== bom.version) {
        throw conflict(
          `BOM \`${key}\` : version \`${previous[1].version}\` (${previous[0]}) vs \`${bom.version}\` (${label})`,
        );
      }
      boms.set(key, [label, bom]);
    }
    for (const dep of contribution.dependencies) {
      if (dep.when !== undefined && !evaluateCondition(dep.when, conditionContext)) continue;
      const key = `${dep.group_id}:${dep.artifact_id}`;
      const previous = dependencies.get(key);
      if (previous) {
        const same =
          previous[1].version === dep.version &&
          (previous[1].scope ?? 'compile') === (dep.scope ?? 'compile') &&
          (previous[1].optional ?? false) === (dep.optional ?? false);
        if (!same) {
          throw conflict(
            `dépendance \`${key}\` déclarée différemment par ${previous[0]} et ${label}`,
          );
        }
        continue;
      }
      dependencies.set(key, [label, dep]);
    }
    for (const [key, value] of Object.entries(contribution.properties)) {
      const previous = properties.get(key);
      if (previous && previous[1] !== value) {
        throw conflict(
          `propriété Maven \`${key}\` : \`${previous[1]}\` (${previous[0]}) vs \`${value}\` (${label})`,
        );
      }
      properties.set(key, [label, value]);
    }
  }
  return {
    boms: [...boms.values()].map(([, b]) => b),
    dependencies: [...dependencies.values()].map(([, d]) => d),
    properties: Object.fromEntries([...properties.entries()].map(([k, [, v]]) => [k, v])),
  };
}

const SPRING_PROPERTY = 'propriété Spring';

export function mergeProperties(
  contributions: readonly [string, PropertiesContribution | undefined][],
): PropertiesContext {
  const result: PropertiesContext = { main: {}, test: {}, profiles: {} };
  for (const [label, contribution] of contributions) {
    if (!contribution) continue;
    for (const [document, tree] of Object.entries(contribution)) {
      if (document === 'main') mergeTree(result.main, tree, '', label, SPRING_PROPERTY);
      else if (document === 'test') mergeTree(result.test, tree, '', label, SPRING_PROPERTY);
      else {
        result.profiles[document] ??= {};
        mergeTree(result.profiles[document], tree, '', label, SPRING_PROPERTY);
      }
    }
  }
  return result;
}

export function sqlTypeFor(column: Column, database: Database): string {
  const length = column.length ?? 255;
  switch (database) {
    case 'postgresql':
      return {
        identity: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        string: `VARCHAR(${length})`,
        text: 'TEXT',
        integer: 'INTEGER',
        bigint: 'BIGINT',
        boolean: 'BOOLEAN',
        timestamp: 'TIMESTAMP WITH TIME ZONE',
        date: 'DATE',
        decimal: 'DECIMAL(19, 4)',
      }[column.type];
    case 'mysql':
      return {
        identity: 'BIGINT AUTO_INCREMENT PRIMARY KEY',
        string: `VARCHAR(${length})`,
        text: 'TEXT',
        integer: 'INT',
        bigint: 'BIGINT',
        boolean: 'BOOLEAN',
        timestamp: 'DATETIME(6)',
        date: 'DATE',
        decimal: 'DECIMAL(19, 4)',
      }[column.type];
    case 'oracle':
      return {
        identity: 'NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        string: `VARCHAR2(${length} CHAR)`,
        text: 'CLOB',
        integer: 'NUMBER(10)',
        bigint: 'NUMBER(19)',
        boolean: 'NUMBER(1)',
        timestamp: 'TIMESTAMP(6) WITH TIME ZONE',
        date: 'DATE',
        decimal: 'NUMBER(19, 4)',
      }[column.type];
    case 'none':
      return '';
  }
}

export function javaTypeFor(column: Column): string {
  return {
    identity: 'Long',
    string: 'String',
    text: 'String',
    integer: 'Integer',
    bigint: 'Long',
    boolean: 'Boolean',
    timestamp: 'Instant',
    date: 'LocalDate',
    decimal: 'BigDecimal',
  }[column.type];
}

export function liquibaseTypeFor(column: Column): string {
  const length = column.length ?? 255;
  return {
    identity: 'BIGINT',
    string: `VARCHAR(${length})`,
    text: 'CLOB',
    integer: 'INT',
    bigint: 'BIGINT',
    boolean: 'BOOLEAN',
    timestamp: 'TIMESTAMP WITH TIME ZONE',
    date: 'DATE',
    decimal: 'DECIMAL(19, 4)',
  }[column.type];
}

/** Clés du contexte propres au pack, ajoutées à la base commune. */
export interface SpringTemplateContext extends BaseTemplateContext {
  project: BaseTemplateContext['project'] & {
    basePackage: string;
    basePackagePath: string;
    groupId: string;
    artifactId: string;
    /** Nom de base de données par défaut : `pay-flow` → `pay_flow`. */
    dbName: string;
  };
  stack: { java: 21 | 17; database: Database; migrations: string | null };
  options: { security: string; docker: boolean; ci: string };
  maven: MavenContext;
  properties: PropertiesContext;
  tables: Table[];
  layers: { id: string; package: string; mayDependOn: string[] }[];
  versions: PinnedVersions;
  sqlType: (column: Column) => string;
  javaType: (column: Column) => string;
  liquibaseType: (column: Column) => string;
  /** Le contexte reste ouvert : les templates lisent des clés que le cœur ne connaît pas. */
  [key: string]: unknown;
}

export function buildSpringContext(
  base: BaseTemplateContext,
  input: PackContextInput,
): TemplateContext {
  const scaffold = asSpringScaffold(input.scaffold);
  const { profile, options } = input;
  const p = profile.profile;
  const basePackage = scaffold.project.base_package;
  const database = scaffold.stack.database;
  const docs = scaffold.language.docs;

  // Contexte réduit servant à évaluer les conditions des dépendances Maven, avant que le
  // contexte complet n'existe.
  const conditionContext: Record<string, unknown> = {
    project: { name: scaffold.project.name, basePackage },
    stack: { java: scaffold.stack.java, database, migrations: scaffold.stack.migrations ?? null },
    profile: profile.id,
    options: scaffold.options,
    optionIds: options.map((o) => o.id),
    git: { agentTrailer: scaffold.git.agent_trailer },
    language: { comments: scaffold.language.comments, docs },
  };

  const maven = mergeMaven(
    [
      [`profiles/${profile.id}`, mavenOf(p)],
      ...options.map((o): [string, MavenContribution | undefined] => [
        `options/${o.id}`,
        mavenOf(o.option),
      ]),
    ],
    conditionContext,
  );
  const properties = mergeProperties([
    [`profiles/${profile.id}`, propertiesOf(p)],
    ...options.map((o): [string, PropertiesContribution | undefined] => [
      `options/${o.id}`,
      propertiesOf(o.option),
    ]),
  ]);
  const context: SpringTemplateContext = {
    ...base,
    project: {
      ...base.project,
      basePackage,
      basePackagePath: basePackage.replace(/\./g, '/'),
      groupId: basePackage,
      artifactId: scaffold.project.name,
      dbName: scaffold.project.name.replace(/-/g, '_'),
    },
    stack: {
      java: scaffold.stack.java,
      database,
      migrations: scaffold.stack.migrations ?? null,
    },
    options: scaffold.options,
    maven,
    properties,
    tables: tablesOf(p.reference_example),
    layers: p.architecture.layers.map((l) => ({
      id: l.id,
      package: l.target.split(BASE_PACKAGE_PLACEHOLDER).join(basePackage),
      mayDependOn: [...l.may_depend_on],
    })),
    versions: PINNED_VERSIONS,
    merge: (tree, contribution) => {
      const result = cloneTree(tree);
      mergeTree(result, contribution, '', 'template', SPRING_PROPERTY);
      return result;
    },
    sqlType: (column) => sqlTypeFor(column, database),
    javaType: javaTypeFor,
    liquibaseType: liquibaseTypeFor,
  };
  return context;
}
